edition:
  date:
    start: "2015/07/18"
    end: "2015/07/20"
  to_html: "July 18<sup>th</sup> to 20<sup>th</sup>"
  venue:
    id: venue_2016

#previous_events:
#  - id: "2015"
#    name: "nucl.ai 2015"